python3 ./code/jn-25.py --jday 100  --p raw --msg " As I sit down to write here amidst "
python3 ./code/jn-25.py --jday 100  --p raw --msg " the shadows of vine-leaves under the blue sky "
python3 ./code/jn-25.py --jday 100  --p raw --msg " of southern Italy, it comes to me with "
python3 ./code/jn-25.py --jday 100  --p raw --msg " a certain quality of astonishment that my participation "
python3 ./code/jn-25.py --jday 100  --p raw --msg " in these amazing adventures of Mr. Cavor was "
python3 ./code/jn-25.py --jday 100  --p raw --msg " the outcome of the purest accident.  It might "
python3 ./code/jn-25.py --jday 100  --p raw --msg " have been any one. I fell into these "
python3 ./code/jn-25.py --jday 100  --p raw --msg " things at a time when I thought myself "
python3 ./code/jn-25.py --jday 100  --p raw --msg " removed from the slightest possibility of disturbing experiences. "
python3 ./code/jn-25.py --jday 100  --p raw --msg " Now is the time for all great space mathematicians to come out and play "